# Generated by Django 4.2.7 on 2025-08-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
    ]
